site_name: Windows Admin Center DSC Resource Module
repo_url: https://github.com/rchaganti/WindowsAdminCenterDsc
theme: readthedocs
pages:
  - Home: index.md
  - WacSetup: WacSetup.md
  - WacFeed: WacFeed.md
  - WacExtension: WacExtension.md
  - WacServerConnection: WacServerConnection.md
  - WacClusterConnection: WacClusterConnection.md
  - WacHciConnection: WacHciConnection.md
